tasks:
  - name: Install dependencies
    init: npm install
    command: npm start
ports:
  - port: 3000
    onOpen: open-preview
    
github:
  prebuilds:
    master: true
    addBadge: true
    addCheck: true
    branches: true
    addComment: false
    pullRequests: true
    pullRequestsFromForks: true
