def gv
pipeline{
    agent any
    stages{
        stage('init Groovy Script'){
            steps{
                script{
                    gv = load 'script.groovy'
                }
            }
        }
        stage('Build'){
            steps{
               script{
                   gv.buildApp()
               }
            }
        }
    }
}