apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-red
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-red
        image: pradumnasaraf/nginx:red
        ports:
        - containerPort: 80
