apiVersion: v1 
kind: Service
metadata:
  name: nginx-service-lb
  namespace: nginx-ns
spec:
  type: LoadBalancer
  selector:
    app: nginx-app
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
