apiVersion: v1 
kind: Service
metadata:
  namespace: deployment-strategies
  name: blue-green-service
spec:
  type: ClusterIP
  selector:
    app: nginx-app
    replica: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80