// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	AuthorID string `json:"authorId"`
	Name     string `json:"name"`
}

type Video struct {
	ID     string  `json:"id" bson:"_id"`
	Title  string  `json:"title"`
	URL    string  `json:"url"`
	Author *Author `json:"author"`
}

type NewVideo struct {
	Title    string `json:"title"`
	URL      string `json:"url"`
	AuthorID string `json:"authorId"`
}
