apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-demo
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:1.26.0
