name: Lint

on:
  workflow_dispatch:
  push:
    paths:
      - "**.js" 
  pull_request:
    paths:
      - "**.js"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checking and cloning the repo
        uses: actions/checkout@v3

      - name: Node Instllation
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
