version: "3.9"

services:
  drupal:
    image: drupal
    ports:
      - 8008:80
    deploy:
      replicas: 3

  database:
    image: postgres
    environment:  
      - POSTGRES_PASSWORD=password
    deploy:
      replicas: 3

