apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pv
  # labels:
  #   type: local
spec:
  storageClassName: standard
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"