apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
  namespace: mongo-express
type: Opaque
data:
  auth-username: YWRtaW4=  # Decodes to "admin"
  auth-password: cGFzc3dvcmQ=  # Decodes to "password"
