name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-20.04
    environment:
      name: preview # Environment is linked here

    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: |
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deployment.txt
        id: deploy

      - name: Extract Deployment URL
        run: |
          DEPLOYMENT_URL=$(tail -n 1 deployment.txt)
          echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> $GITHUB_ENV
        id: extract-url

      # Step to set URL for the deployment manually
      - name: Update Environment URL
        if: success()
        run: echo "::set-output name=environment_url::${{ env.DEPLOYMENT_URL }}"
        env:
          DEPLOYMENT_URL: "https://google.com"
