apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  resources:
    requests:
      storage: 500Mi
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
